[build]
  command = "npm run build"
  publish = "dist"

# SPA重定向规则
[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/lovable-uploads/*"
  to = "/lovable-uploads/:splat"
  status = 200

# APP封装文件
[[redirects]]
  from = "/yimen-app.html"
  to = "/yimen-app.html"
  status = 200

[[redirects]]
  from = "/clip-426251-35739.html"
  to = "/clip-426251-35739.html"
  status = 200

# SPA回退规则 - 必须放在最后
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部配置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Supabase CORS支持
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, apikey, x-client-info"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 环境变量配置说明
[build.environment]
  # 确保Supabase环境变量在构建时可用
  # VITE_SUPABASE_URL 和 VITE_SUPABASE_ANON_KEY 
  # 应该在Netlify部署设置中配置
